// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPTgmgVm8j_rao8H91VH0CkabEg_q39YQ',
    appId: '1:668489064929:web:fa7a0c000bdf3a0a8932a0',
    messagingSenderId: '668489064929',
    projectId: 'zevils-5a935',
    authDomain: 'zevils-5a935.firebaseapp.com',
    storageBucket: 'zevils-5a935.appspot.com',
    measurementId: 'G-VRM7DVZ89M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlmDrqAgbjLlxJ57ZLnur1LcJDZMBuP4',
    appId: '1:668489064929:android:63de98960cac124c8932a0',
    messagingSenderId: '668489064929',
    projectId: 'zevils-5a935',
    storageBucket: 'zevils-5a935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcgwQmShuG1026r2p_5iS11nsPfraghWM',
    appId: '1:668489064929:ios:967a6b4ccef0943c8932a0',
    messagingSenderId: '668489064929',
    projectId: 'zevils-5a935',
    storageBucket: 'zevils-5a935.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcgwQmShuG1026r2p_5iS11nsPfraghWM',
    appId: '1:668489064929:ios:48c475dc729b49448932a0',
    messagingSenderId: '668489064929',
    projectId: 'zevils-5a935',
    storageBucket: 'zevils-5a935.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
